### ISSUE TITLE
displaying dates

### ISSUE THREAD

**Issue by JO0st** [Alecaddd/sequeler#66]
I have a database with a table in it that contains some fields of the type date. When issuing a query on that table the dates don't get displayed. 

I attached screenshots from both sequeler and dbeaver issueing the same query to the same database.

![image](https://user-images.githubusercontent.com/4729613/34432641-5d9fc5b6-ec79-11e7-8c31-424f14bbce12.png)
![image](https://user-images.githubusercontent.com/4729613/34432648-767b17e8-ec79-11e7-9f93-1896e0e9afb2.png)

**Comment by Alecaddd** [comment]
Thanks for the report, that's definitely a bug!
Would you be able to share with me the raw data? I don't need the entire table, just a couple of rows with the same data format, in order for me to test it locally.
Cheers

**Comment by JO0st** [comment]
I attached a create table script with a table containing some of the problematic data
[test_data.sql.txt](https://github.com/Alecaddd/sequeler/files/1597068/test_data.sql.txt)

**Comment by Alecaddd** [comment]
I pushed a new version to the AppCenter that should fix the problem, I'll test your data later today and see if it works.
Thanks

**Comment by Alecaddd** [comment]
So, the problem happens because the field `date` has a set type of `datetime`, which the correct format is `YYYY-MM-DD HH:MM:SS`.
You're saving just the date format `YYYY-MM-DD`, which is ok for the database itself, and the majority of the software out there.
Unfortunately, Sequeler uses `LibGda`, which as you noticed it doesn't handle properly entries that don't exactly match the data type specified in the field.
I'll look around and try to find a solution.

**Comment by btd1337** [comment]
Try to do a check 

```
if (HH:MM:SS == null) {
    HH:MM:SS = 00:00:00
}
```

**Comment by Alecaddd** [comment]
That's not how Vala or the LibGDA works, that check can't be done, and I shouldn't do if statements for specific conditions, the code won't be scalable.

**Comment by olivierberten** [comment]
Just to confirm this is still a problem when using DATE field instead of DATETIME. In my case, it just displays the content of the previous column.

**Comment by nickelghost** [comment]
It also displays the previous column for me:
![screenshot from 2019-02-02 14-25-23](https://user-images.githubusercontent.com/16365643/52165335-61bc0380-26f7-11e9-83b6-5c4b89222a2b.png)

**Comment by mikeymop** [comment]
Same as @nickelghost 
![Screenshot from 2019-05-06 17-52-17](https://user-images.githubusercontent.com/4002969/57257576-dcaef600-7027-11e9-85b9-46c2b2d22656.png)

**Comment by weop** [comment]
This bug is present in v0.7.0. db: MariaDB 10. like the others have reported. It's showing the previous columns value instead of the date field.

**Comment by gravyTrainee** [comment]
This issue is still present as of 00e5f7b471.

In case it helps, this line is getting logged repeatedly:

```
(Sequeler:11902): GLib-GObject-WARNING **: 13:29:55.530: unable to set property 'text' of type 'gchararray' from value of type 'GDate'
```
